# -*- coding: utf-8 -*-


FUTURE_CONTRACT_USDT_UMCBL = "umcbl"
FUTURE_CONTRACT_USDT_DMCBL = "dmcbl"
FUTURE_CONTRACT_USDT_CMCBL = "cmcbl"
FUTURE_CONTRACT_USDT_SUMCBL = "sumcbl"
FUTURE_CONTRACT_USDT_SDMCBL = "sdmcbl"
FUTURE_CONTRACT_USDT_SCMCBL = "scmcbl"
MARIN_COIN = "USDT"
MARGIN_MODE = "fixed"


OBSERVE_COIN_LIST = []
REMOVE_COIN_LIST = ["USDC"]

#QUOTE_ASSET = "USDT"
PAIR_ASSET_DEFAULT = "USDT"  # Par de comparación por defecto para la compra/venta de monedas ej: Si moneda = BTC y par = USDT -> BTCUSDT
MAX_COIN_BUY = 1
QUANTITY_BUY_ORDER = 15

#CUSTOM
API_KEY_BIT = 
API_SECRET_BIT = 
API_PASSPHRASE_BIT = 

TELEGRAM_BOT_TOKEN = 
CHATID = 