
BITGET_CLIENT_TEST_MODE = true
LOAD_FROM_PREVIOUS_EXECUTION = false

MAX_COIN_BUY = 4
QUANTITY_BUY_ORDER = 100

OBSERVE_COIN_LIST = []
REMOVE_COIN_LIST = ["ETH","XMR","AUD","LUNA","BNB","PEPE"]

FUTURE_CONTRACT = "umcbl" # "dmcbl" "cmcbl" "sumcbl" "sdmcbl" "scmcbl"
MARGINCOIN = "USDT"

FILES_BASE_PATH = "C:\\MIO\\Particular\\Python\\boTraidingBidget\\"

TELEGRAM_BOT_TOKEN = "xxx"
CHATID = "xxx"
