# COMPRA
API_KEY_BIT = "bg_40c06763880f233e7f5f67b2cc38da10"
API_SECRET_BIT = "e39392e87f3cf402c6f4f1eb27656f5d6b4d90eb8db36e6b812b580515aa8ee0"
API_PASSPHRASE_BIT = "TheBestDaniel"
BITGET_CLIENT_TEST_MODE = true
LOAD_FROM_PREVIOUS_EXECUTION = false

MAX_COIN_BUY = 1
QUANTITY_BUY_ORDER = 300

OBSERVE_COIN_LIST = []
REMOVE_COIN_LIST = ["ETH","XMR","AUD","LUNA","BNB","PEPE"]

FUTURE_CONTRACT = "umcbl" # "dmcbl" "cmcbl" "sumcbl" "sdmcbl" "scmcbl"
MARGINCOIN = "USDT"

FILES_BASE_PATH = "C:\\top-workspace\\boTraiding\\"

TELEGRAM_BOT_TOKEN = "5493985124:AAGYAl2I_0_UP0oDd7BmXp-wDHfxj2GMqpo"
CHATID = "5150168061"
