
BINANCE_CLIENT_TEST_MODE = true
MAX_COIN_BUY = 4
QUANTITY_BUY_ORDER = 300
LOAD_FROM_PREVIOUS_EXECUTION = false
OBSERVE_COIN_LIST = []
REMOVE_COIN_LIST = ["ETH","XMR","AUD","LUNA","BNB","PEPE", "BTC"]

FILES_BASE_PATH = "C:\\top-workspace\\boTraiding\\"

TELEGRAM_BOT_TOKEN = "xxx"
CHATID = "xxx"

BO_TRADING_API_KEY_BIN = "xxx"
BO_TRADING_SECRET_KEY_BIN = "xxx"