# COMPRA
BITGET_CLIENT_TEST_MODE = false
LOAD_FROM_PREVIOUS_EXECUTION = false

MAX_COIN_BUY = 1
QUANTITY_BUY_ORDER = 20

OBSERVE_COIN_LIST = ["BTC","XRP","ETH","SOL","ADA","BIGTME","PEOPLE","STX","TIA"]
#OBSERVE_COIN_LIST = []
REMOVE_COIN_LIST = ["XMR","AUD","LUNA","BNB","PEPE"]

FUTURE_CONTRACT = "umcbl" # "dmcbl" "cmcbl" "sumcbl" "sdmcbl" "scmcbl"
MARGIN_MODE = "fixed" #"crossed"
MARGINCOIN = "USDT"

FILES_BASE_PATH = "C:\\MIO\\Particular\\Python\\boTraidingBidget\\"


